framework:
    messenger:
        default_bus: command.bus

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        buses:
            command.bus:
                middleware:

            query.bus:
                middleware:

            job.queue:
                default_middleware: allow_no_handlers
                middleware:

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            job_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/job_queue'
                options:
                    exchange:
                        name: job_queue
                        type: direct
                        durable: true

        routing:
            # Route your messages to the transports
            Somnambulist\Components\Domain\Commands\AbstractCommand: sync
            Somnambulist\Components\Domain\Queries\AbstractQuery: sync
            Somnambulist\Components\Domain\Jobs\AbstractJob: job_queue
