security:
    password_hashers:
        App\Auth\Domain\Models\SecurityUser:
            algorithm: bcrypt
            cost: 14

    providers:
        security_users:
            id: App\Auth\Infrastructure\Services\SecurityUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            user_checker: App\Auth\Infrastructure\Services\SecurityUserChecker
            form_login:
                enable_csrf: true
                login_path: auth.login
                check_path: auth.login
            logout:
                path:   auth.logout
                target: auth.login
            switch_user: { role: ROLE_SWITCH_USER }

    access_control:
        - { path: ^/auth/login, roles: ACCESS_PUBLIC }
        - { path: ^/auth/lost_password, roles: ACCESS_PUBLIC }
        - { path: ^/auth/reset_password/*, roles: ACCESS_PUBLIC }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
