somnambulist_api:
    exception_handler:
        converters:
            Assert\InvalidArgumentException: Somnambulist\Bundles\ApiBundle\Services\Converters\AssertionExceptionConverter
            Assert\LazyAssertionException: Somnambulist\Bundles\ApiBundle\Services\Converters\LazyAssertionExceptionConverter
            Symfony\Component\Messenger\Exception\HandlerFailedException: Somnambulist\Bundles\ApiBundle\Services\Converters\HandlerFailedExceptionConverter
    subscribers:
        exception_to_json: false
        json_to_post: true
        request_id: true
