version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: config/docker/test/app/Dockerfile
    depends_on:
      - postgres
    networks:
      - backend

  app-redis:
    image: redis:alpine
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmqcookienamehere
    networks:
      - backend

  app-web:
    build:
      context: .
      dockerfile: config/docker/test/web/Dockerfile
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
