version: '3.7'

services:
  app-server:
    build:
      context: .
      dockerfile: config/docker/dev/app/Dockerfile
    networks:
      - mycompany_network_backend

  app-cache:
    image: redis:alpine
    networks:
      - mycompany_network_backend

  app-sessions:
    image: redis:alpine
    networks:
      - mycompany_network_backend

  app-web:
    build:
      context: .
      dockerfile: config/docker/dev/web/Dockerfile
    depends_on:
      - app-server
    networks:
      - mycompany_network_backend
    labels:
      traefik.enable: true
      traefik.http.routers.app-web.rule: "Host(`app.example.dev`)"
      traefik.http.routers.app-web.tls: true
      traefik.http.services.app-web.loadbalancer.server.port: 8080

networks:
  mycompany_network_backend:
    external: true
